controller:
  additionalPlugins:
    - docker-plugin:1.2.3
    - workflow-multibranch:2.26
    - email-ext:2.83
    - parameterized-trigger:2.41
    - greenballs:1.15.1
    - docker-workflow:1.26

backup:
  enabled: true
  schedule: "*/5 * * * *" 
  destination: "s3://internship-first-bucket/jenkins-backup/" 
  env: 
    - name: "AWS_REGION"
      value: "us-east-2"
  serviceAccount:
    create: true
    name: "jenkins-sa"
    annotations: 
        iam.amazonaws.com/role: "jenkins-rw-bucket-rights"
        eks.amazonaws.com/role-arn: "arn:aws:iam::113304117666:role/jenkins-rw-bucket-rights"