- hosts: localhost
  tasks:
  - name: pull worker
    docker_image:
      name: 113304117666.dkr.ecr.us-east-2.amazonaws.com/worker:latest
      source: pull
  - name: pull result
    docker_image:
      name: 113304117666.dkr.ecr.us-east-2.amazonaws.com/result:latest
      source: pull
  - name: pull seed-data
    docker_image:
      name: 113304117666.dkr.ecr.us-east-2.amazonaws.com/seed-data:latest
      source: pull
  - name: pull vote
    docker_image:
      name: 113304117666.dkr.ecr.us-east-2.amazonaws.com/vote:latest
      source: pull
  