apiVersion: v1
kind: Service
metadata:
  name: resultservice-service
  labels:
    app: resultservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: resultservice