
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultservice-deployment
spec:
  selector:
    matchLabels:
      app: resultservice
  replicas: 1 # only have one replica as this microservice uses an in-memory backing database
  template:
    metadata:
      labels:
        app: resultservice
    spec:
      containers:
      - name: resultservice
        image: 113304117666.dkr.ecr.us-east-2.amazonaws.com/result:latest
        ports:
        - containerPort: 8080