apiVersion: v1
kind: Service
metadata:
  name: seed-dataservice-service
  labels:
    app: seed-dataservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: seed-dataservice