apiVersion: v1
kind: Service
metadata:
  name: voteservice-service
  labels:
    app: voteservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: voteservice